{% set name = "torchtext-base" %}
{% set version = "0.16.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/pytorch/text.git
  git_rev: v{{ version }}
  patches:
    # 01xx - patch is specific to open-ce and will always be carried forward and not upstreamed
    - 0101-disable-tcmalloc.patch

build:
  number: 3
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']
  script_env:                                    #[ppc_arch == 'p10']
    - GCC_HOME                                #[ppc_arch == 'p10']

requirements:
  build:
    - {{ compiler('cxx') }}               #[ppc_arch != "p10"]
    - cmake {{ cmake }}
    - make
    - patch
    - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
  host:
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
  run:
    - numpy {{ numpy }}
    - python {{ python }}
    - _pytorch_select  {{ pytorch_select_version }}
    - pytorch-base     {{ pytorch }}
    - requests {{ requests }}
    - tqdm {{ tqdm }}
    - sentencepiece {{ sentencepiece }}
    - torchdata
    - cudatoolkit {{ cudatoolkit }}            #[build_type == 'cuda']
test:
  imports:
    - torchtext
    - torchtext.data
    - torchtext.datasets

about:
  home: https://github.com/pytorch/text
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Text utilities and datasets for PyTorch
  description: Text utilities and datasets for PyTorch
  doc_url: https://torchtext.readthedocs.io/en/latest/
  dev_url: https://github.com/pytorch/text/

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
